[package]
name = "hk-charm-calc"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.6"
tokio = { version = "1.26", features = ["full"] }
tower-http = { version = "0.4", features = ["full"] }
